/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package Deployment;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class Red Hat Enterprise Linux Advanced Server 6.0 
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class Red Hat Enterprise Linux Advanced Server 6.0  {
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Red Hat Enterprise Linux Advanced Server 6.0 () {
		super();
	}
	
}
