/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package Deployment;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class Sun SPARC Server
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class Sun SPARC Server {
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Sun SPARC Server() {
		super();
	}
	
}
