/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package Interfaces;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the interface Auth.
 * 
 * @generated
 */
public interface Auth {
	/**
	 * The documentation of the method login.
	 * 
	 * @param agency
	 * @param user
	 * @param pwd
	 * 
	 * @generated
	 */
	public void login(TravelPortal agency, String user, String pwd);
	
}
