/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package Interfaces;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the interface Customers.
 * 
 * @generated
 */
public interface Customers {
	/**
	 * The documentation of the method findByName.
	 * 
	 * @param partialName
	 * 
	 * @generated
	 */
	public void findByName(String partialName);
	
}
