/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package Interfaces;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the enumeration ReservationStatus.
 * 
 * @generated
 */
public enum ReservationStatus {
	/**
	 * The documentation of the enumeration literal RESERVATIONSTATUS.
	 * 
	 * @generated
	 */
	RESERVATIONSTATUS,
	
	/**
	 * The documentation of the enumeration literal RESERVATIONSTATUS.
	 * 
	 * @generated
	 */
	RESERVATIONSTATUS,
	
	/**
	 * The documentation of the enumeration literal RESERVATIONSTATUS.
	 * 
	 * @generated
	 */
	RESERVATIONSTATUS,
	
	/**
	 * The documentation of the enumeration literal RESERVATIONSTATUS.
	 * 
	 * @generated
	 */
	RESERVATIONSTATUS,
	
}
