/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package Interfaces;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the interface Travels.
 * 
 * @generated
 */
public interface Travels {
	/**
	 * The documentation of the method findByDestination.
	 * 
	 * @param partialName
	 * @return
	 * 
	 * @generated
	 */
	public Travel findByDestination(String partialName);
	
}
