/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package Behaviours;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class StateMachine
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class StateMachine {
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public StateMachine() {
		super();
	}
	
}
