/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package Components;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class Agency  Offers
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class Agency  Offers implements Travels {
	/**
	 * The documentation of the attribute agency  OffersPort.
	 * 
	 * @generated
	 */
	private Agency  Offers agency  OffersPort;
	
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Agency  Offers() {
		super();
	}
	/**
	 * The documentation of the method findByDestination.
	 * 
	 * @param partialName
	 * @return
	 * 
	 * @generated
	 */
	public Travel findByDestination(String partialName) {
		// Start of user code for the body of findByDestination
		// TODO should be implemented
		return null;
		// End of user code
	}
	
	
	/**
	 * The documentation of the getter getAgency  OffersPort.
	 * 
	 * @generated
	 */
	public Agency  Offers getAgency  OffersPort() {
		return this.agency  OffersPort;
	}
	
	/**
	 * The documentation of the setter setAgency  OffersPort.
	 * 
	 * @generated
	 */
	public void setAgency  OffersPort(Agency  Offers newAgency  OffersPort) {
		this.agency  OffersPort = newAgency  OffersPort;
	}
}
