/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package Components;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class Booking System
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class Booking System implements ReservationSearch {
	/**
	 * The documentation of the attribute booking SystemPort.
	 * 
	 * @generated
	 */
	private Booking System booking SystemPort;
	
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Booking System() {
		super();
	}
	/**
	 * The documentation of the method get.
	 * 
	 * @param customer
	 * @return
	 * 
	 * @generated
	 */
	public Booking get(Customer customer) {
		// Start of user code for the body of get
		// TODO should be implemented
		return null;
		// End of user code
	}
	
	/**
	 * The documentation of the method findByTravel.
	 * 
	 * @param travel
	 * @return
	 * 
	 * @generated
	 */
	public Booking findByTravel(Travel travel) {
		// Start of user code for the body of findByTravel
		// TODO should be implemented
		return null;
		// End of user code
	}
	
	
	/**
	 * The documentation of the getter getBooking SystemPort.
	 * 
	 * @generated
	 */
	public Booking System getBooking SystemPort() {
		return this.booking SystemPort;
	}
	
	/**
	 * The documentation of the setter setBooking SystemPort.
	 * 
	 * @generated
	 */
	public void setBooking SystemPort(Booking System newBooking SystemPort) {
		this.booking SystemPort = newBooking SystemPort;
	}
}
