/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package Components;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class CRM
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class CRM implements Customers {
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public CRM() {
		super();
	}
	/**
	 * The documentation of the method findByName.
	 * 
	 * @param partialName
	 * 
	 * @generated
	 */
	public void findByName(String partialName) {
		// Start of user code for the body of findByName
		// TODO should be implemented
		// End of user code
	}
}
