/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package Components;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class Internal Authentification
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class Internal Authentification implements Auth {
	/**
	 * The documentation of the attribute authService.
	 * 
	 * @generated
	 */
	private Internal Authentification authService;
	
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Internal Authentification() {
		super();
	}
	/**
	 * The documentation of the method login.
	 * 
	 * @param agency
	 * @param user
	 * @param pwd
	 * 
	 * @generated
	 */
	public void login(TravelPortal agency, String user, String pwd) {
		// Start of user code for the body of login
		// TODO should be implemented
		// End of user code
	}
	
	
	/**
	 * The documentation of the getter getAuthService.
	 * 
	 * @generated
	 */
	public Internal Authentification getAuthService() {
		return this.authService;
	}
	
	/**
	 * The documentation of the setter setAuthService.
	 * 
	 * @generated
	 */
	public void setAuthService(Internal Authentification newAuthService) {
		this.authService = newAuthService;
	}
}
