/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package Components;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class Supplier Purchasing
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class Supplier Purchasing {
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Supplier Purchasing() {
		super();
	}
	
}
